In [30]:
import pandas as pd
import numpy as np
import collections

In [51]:
stage2_df = pd.read_csv("stage2.csv")

In [54]:
# produce a matrix
article_index = [str(i) for i in list(stage2_df.Num)]
#test_matrix = pd.DataFrame(data=result_arr, index=article_index, columns=test_df[0])

In [55]:
article_index

['1001',
 '1004',
 '1006',
 '1008',
 '1009',
 '1012',
 '1014',
 '1019',
 '102',
 '1022',
 '1024',
 '1027',
 '1028',
 '1029',
 '1032',
 '1034',
 '1036',
 '1038',
 '1040',
 '1048',
 '1050',
 '1051',
 '1053',
 '1060',
 '1061',
 '1062',
 '1063',
 '1064',
 '1070',
 '1072',
 '1080',
 '1081',
 '1084',
 '1085',
 '1089',
 '109',
 '1091',
 '1092',
 '1094',
 '1095',
 '1097',
 '1098',
 '1105',
 '1106',
 '111',
 '1113',
 '112',
 '1121',
 '1123',
 '1124',
 '1129',
 '1131',
 '1135',
 '1137',
 '114',
 '1140',
 '1143',
 '1156',
 '1158',
 '116',
 '1162',
 '1163',
 '1164',
 '1175',
 '1177',
 '1182',
 '1188',
 '1196',
 '1197',
 '1201',
 '1202',
 '1203',
 '1204',
 '1205',
 '1209',
 '1213',
 '1216',
 '1219',
 '122',
 '1225',
 '1227',
 '123',
 '1231',
 '1233',
 '1238',
 '124',
 '1245',
 '125',
 '1251',
 '1252',
 '1254',
 '1268',
 '1269',
 '1273',
 '1277',
 '128',
 '1284',
 '1285',
 '1287',
 '1288',
 '1295',
 '1296',
 '1299',
 '13',
 '130',
 '1303',
 '1306',
 '1307',
 '1313',
 '1316',
 '1317',
 '1318',
 '132',
 '1325',
 '1328',
 '1330',
 '1336',
 '1338',
 '134',
 '1344',
 '1345',
 '1346',
 '1349',
 '1351',
 '1353',
 '1360',
 '1368',
 '137',
 '1371',
 '1376',
 '1380',
 '1383',
 '1384',
 '1385',
 '1387',
 '1388',
 '1389',
 '1393',
 '1398',
 '1399',
 '1400',
 '143',
 '145',
 '148',
 '153',
 '159',
 '160',
 '161',
 '162',
 '164',
 '165',
 '168',
 '172',
 '175',
 '177',
 '187',
 '19',
 '190',
 '192',
 '193',
 '195',
 '198',
 '20',
 '200',
 '202',
 '206',
 '213',
 '214',
 '216',
 '229',
 '233',
 '234',
 '24',
 '244',
 '245',
 '247',
 '249',
 '250',
 '254',
 '257',
 '264',
 '265',
 '269',
 '270',
 '272',
 '277',
 '28',
 '281',
 '287',
 '288',
 '290',
 '293',
 '294',
 '30',
 '304',
 '309',
 '31',
 '312',
 '315',
 '324',
 '331',
 '334',
 '335',
 '339',
 '345',
 '350',
 '352',
 '358',
 '359',
 '363',
 '366',
 '367',
 '376',
 '38',
 '385',
 '388',
 '389',
 '390',
 '393',
 '394',
 '397',
 '398',
 '399',
 '401',
 '404',
 '407',
 '408',
 '409',
 '410',
 '413',
 '414',
 '416',
 '417',
 '42',
 '420',
 '423',
 '426',
 '427',
 '430',
 '433',
 '435',
 '439',
 '440',
 '443',
 '445',
 '447',
 '45',
 '450',
 '451',
 '452',
 '454',
 '459',
 '460',
 '461',
 '462',
 '464',
 '469',
 '473',
 '477',
 '485',
 '488',
 '489',
 '490',
 '491',
 '494',
 '497',
 '499',
 '50',
 '503',
 '506',
 '514',
 '518',
 '52',
 '525',
 '526',
 '528',
 '533',
 '534',
 '535',
 '538',
 '545',
 '547',
 '56',
 '563',
 '564',
 '570',
 '573',
 '574',
 '579',
 '580',
 '581',
 '589',
 '592',
 '593',
 '60',
 '600',
 '615',
 '617',
 '618',
 '624',
 '625',
 '627',
 '634',
 '640',
 '643',
 '647',
 '648',
 '651',
 '655',
 '660',
 '664',
 '666',
 '668',
 '669',
 '671',
 '681',
 '685',
 '688',
 '69',
 '697',
 '699',
 '7',
 '702',
 '705',
 '706',
 '707',
 '71',
 '712',
 '714',
 '717',
 '718',
 '723',
 '728',
 '731',
 '734',
 '738',
 '739',
 '74',
 '742',
 '745',
 '748',
 '749',
 '750',
 '752',
 '754',
 '758',
 '761',
 '762',
 '765',
 '766',
 '770',
 '772',
 '777',
 '778',
 '79',
 '796',
 '798',
 '80',
 '801',
 '803',
 '813',
 '814',
 '815',
 '818',
 '820',
 '822',
 '828',
 '831',
 '833',
 '834',
 '84',
 '844',
 '852',
 '854',
 '859',
 '861',
 '867',
 '869',
 '87',
 '873',
 '880',
 '881',
 '886',
 '889',
 '894',
 '896',
 '90',
 '901',
 '903',
 '908',
 '909',
 '910',
 '915',
 '917',
 '92',
 '926',
 '927',
 '928',
 '929',
 '930',
 '935',
 '937',
 '938',
 '939',
 '941',
 '943',
 '96',
 '960',
 '965',
 '970',
 '972',
 '975',
 '980',
 '985',
 '987',
 '990',
 '991',
 '993',
 '994',
 '996',
 '999']

In [18]:
result_arr = np.load("result_test.npy")

In [19]:
result_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
len(result_arr)

421

In [27]:
for next_art in range(len(result_arr)):
    print(next_art)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420

In [32]:
type(range(len(result_arr)))

range

In [28]:
result_arr[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
result_df = pd.DataFrame({'Test':[], 'Reference': [], 'Similarity(%)': []})

In [39]:
result_df

Empty DataFrame
Columns: [Test, Reference, Similarity(%)]
Index: []

In [44]:
dict = {'Test': '3', 'Reference': '5', 'Similarity(%)': 95}
result_df.append(dict, ignore_index=True)

  Test Reference  Similarity(%)
0    3         5           95.0

In [53]:
stage2_df.Num

0      1001
1      1004
2      1006
3      1008
4      1009
       ...
416     991
417     993
418     994
419     996
420     999
Name: Num, Length: 421, dtype: int64

In [68]:
result_df = pd.DataFrame({'Test':[], 'Reference': [], 'Similarity(%)': []})
count = 0
similarity_list=[]
for article_vec in result_arr:
    for next_idx in range(len(result_arr)):
        next_vec = result_arr[next_idx]
        article_vec
        agg_array = np.bitwise_and(article_vec, next_vec)
        both_array_num = collections.Counter(agg_array)[1]
        sing_array_num = collections.Counter(article_vec)[1]
        if sing_array_num == 0:
            similarity = 0
        else:
            similarity = both_array_num/sing_array_num*100
        dict = {'Test': article_index[count], 'Reference': article_index[next_idx], 'Similarity(%)': similarity}
        result_df = result_df.append(dict, ignore_index=True)
    count+=1

In [69]:
result_df.to_csv("Test Label Results.csv", index= False)

In [80]:
result_df.iloc[176818]

Test             996
Reference        996
Similarity(%)    100
Name: 176818, dtype: object

In [88]:
filtered_df = result_df

In [89]:
self_ref = list(range(0, 177662, 422))

In [90]:
filtered_df = filtered_df.drop(self_ref)

In [92]:
filtered_df.to_csv("Test Results Filtered-1.csv", index=False)

In [96]:
filtered_df

        Test Reference  Similarity(%)
1       1001      1004            0.0
2       1001      1006            0.0
3       1001      1008           25.0
4       1001      1009           25.0
5       1001      1012            0.0
...      ...       ...            ...
177235   999       990            0.0
177236   999       991            0.0
177237   999       993            0.0
177238   999       994            0.0
177239   999       996            0.0

[176820 rows x 3 columns]

In [100]:
last_result_df = filtered_df.loc[filtered_df["Similarity(%)"] >= 93.36].reset_index()
del last_result_df['index']
del last_result_df['Similarity(%)']

In [101]:
last_result_df

     Test Reference
0    1001      1019
1    1001      1022
2    1001      1034
3    1001      1040
4    1001      1091
..    ...       ...
970   960       889
971   991       407
972   991       615
973   991       908
974   991       990

[975 rows x 2 columns]

In [102]:
last_result_df.to_csv("Last Results.csv", index=False)

In [37]:
similarity_list

[100.0, 0.0, 0.0, 25.0, 25.0]

In [ ]:
import collections, numpy
similarity_list=[]
b = 0

# similarity = the num of repeated keywords in two file (test & reference)/ the num of keywords in the test file
for a in range (len(label_df.index)):
    i = int(label_df.iloc[a]['Test'])
    j = int(label_df.iloc[a]['Reference'])
    iv = int(article_df.loc[article_df.Num == i].index[0])
    jv = int(article_df.loc[article_df.Num == j].index[0])
    agg_array = np.bitwise_and(result_arr[iv], result_arr[jv])
    agg_array_num = collections.Counter(agg_array)[1]
    sing__array_num = collections.Counter(result_arr[iv])[1]
    if sing__array_num == 0:
        similarity = 0
    else:
        similarity = agg_array_num/sing__array_num*100
    similarity_list.append(similarity)